name: Build and Push Docker Image for Mateo Murillo

on:
  push:
    branches: [ "mateomurillo" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-hola-mundo:1.0.0 .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-hola-mundo:1.0.0
